name: lodestar
description: compatibility calculator.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  copy_with_extension: ^4.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  proste_route_animation: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.1
  copy_with_extension_gen: ^4.0.3
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.10+1
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/dancing_script.ttf
    - family: Lato
      fonts:
        - asset: assets/Lato-Regular.ttf

flutter_native_splash:
  color: '#ffffff'
  image: splash.png
